POST https://api.instagram.com/oauth/access_token
Content-Type: application/x-www-form-urlencoded

client_id=776958943480583
&client_secret=07dac85cee6ede417a6268ccefa0b169
&grant_type=authorization_code
&redirect_uri=https://0xlink-navneetpal718-gmailcom.vercel.app/
&code=AQBb9FeBC5rWneYGxraM6r4CtW9F97gsQ-i6VKWPN83jMc5VQoPurhE5JgYM8_a7336ij68EnL4E8PHvK330tx6iVWypEcbrhgfyHXnM5VpSzxDdL9IIZ2CRoUvoFk9j_ezHUoZLbsqJNATlch3uuCqLxhHvJX_ZB0R_L-nz5Mc7cSj9XdnXjMml3xaPZLiqPda823pljt2q0v3f9XUHNbI36KScnO_dDmkXDMTh9BomSw


###

GET https://graph.instagram.com/access_token?grant_type=ig_exchange_token&client_secret=07dac85cee6ede417a6268ccefa0b169&access_token=IGQVJWNEdYUVlJNUgzdzczRUtQcnpqOVVkLW9rTnRoT3BPbmtrWVVhQXg2bTltV1U2NmNLeTRMYVVaeHc4ZA3REQ1YwM2xxUkx6RUt4akw1d1FLajVGTTlLWDhpbjhZARk5mNXZAEWGlfSDFMdmJjWThGcGZAxcXVuWFltZAVU0

###
GET https://graph.instagram.com/me?fields=id,username&access_token=IGQVJWNEdYUVlJNUgzdzczRUtQcnpqOVVkLW9rTnRoT3BPbmtrWVVhQXg2bTltV1U2NmNLeTRMYVVaeHc4ZA3REQ1YwM2xxUkx6RUt4akw1d1FLajVGTTlLWDhpbjhZARk5mNXZAEWGlfSDFMdmJjWThGcGZAxcXVuWFltZAVU0